### ISSUE TITLE
Issue with Storybook V6.3

### ISSUE THREAD

**Issue by abhi-qb** [stevensacks/storybook-react-i18next#1]
Hi, I tried following all the steps, but it throws an error saying:

`Storybook preview hooks can only be called inside decorators and story functions.`

Any ways to fix this? @stevensacks

**Comment by stevensacks** [comment]
I've never seen that error before. It might have something to do with a dependency. Have you tried googling? Can you provide any more detail about your project configuration?

**Comment by abhi-qb** [comment]
Hi @stevensacks sorry for late reply, 
I tried adding the code in addon:
`"storybook-react-i18next"`

Then I created a file named i18next.js with necessary modifications I need as mentioned [here](https://github.com/stevensacks/storybook-react-i18next#i18nextjs)

Then  I added parameters in preview.js
```
import { addParameters } from "@storybook/react";
import {i18n} from './i18next.js';

addParameters({
  i18n,
  locale: 'en',
  locales: {
    en: 'English',
    jp: '日本語',    
  },
})
```

But It is showing the above mentioned error @stevensacks

**Comment by wentjun** [comment]
Hi, I am facing the same issue with the default configurations stated on the README.

Whenever I have any Story that uses `useState` and the state is updated while interacting with the component in the Story, the error will be thrown.

Stack trace:

```
Storybook preview hooks can only be called inside decorators and story functions.
Error: Storybook preview hooks can only be called inside decorators and story functions.
    at invalidHooksError (http://localhost:6006/vendors~main.iframe.bundle.js:34563:10)
    at useStoryContext (http://localhost:6006/vendors~main.iframe.bundle.js:34765:11)
    at useGlobals (http://localhost:6006/vendors~main.iframe.bundle.js:34810:27)
    at withI18Next (http://localhost:6006/vendors~main.iframe.bundle.js:155772:101)
    at http://localhost:6006/vendors~main.iframe.bundle.js:34509:21
    at http://localhost:6006/vendors~main.iframe.bundle.js:36499:12
    at http://localhost:6006/vendors~main.iframe.bundle.js:36535:16
    at renderWithHooks (http://localhost:6006/vendors~main.iframe.bundle.js:131804:18)
    at updateFunctionComponent (http://localhost:6006/vendors~main.iframe.bundle.js:134175:20)
    at beginWork (http://localhost:6006/vendors~main.iframe.bundle.js:135882:16)

```

**Comment by stevensacks** [comment]
Just to confirm, it is assumed you already have i18next and react-i18next and their associated packages already set up in your project and that it's working in your project before you add this add on to storybook.

https://www.i18next.com/overview/getting-started

https://react.i18next.com/getting-started

This addon does not include any of the i18next or react-i18next packages, however, I realized that it didn't have `i18next-browser-languagedetector` and `i18next-http-backend` listed as peerDependencies. This will be added in the next release.

**Comment by stevensacks** [comment]
If you are still experiencing issues, could you please create a minimal repository where you replicate the issue and share it with me?

**Comment by jacobgranberry** [comment]
Hey there!  So the above solutions worked for me - using {Story()} on a global decorator - however I have another addon I use that requires using `addDecorator` in preview.js.  When its included, I get the original error about Storybook preview hooks, but when I comment out the `addDecorator` function it works fine.

**Comment by wentjun** [comment]
@stevensacks apologies for the late reply - I am currently unable to verify as I have left my previous job and lost access to their codebase. Looking at the other answers, it seems like `{Story()}` would have solved my issues!

**Comment by mingaldrichgan** [comment]
`{Story()}` seems like a band-aid as it removes the error but also the ability to switch languages on the fly.

**Comment by stevensacks** [comment]
As far as I can tell, this issue has been fixed in the latest release (which is compatible with Storybook 6.4.x).

**Comment by wangdianwen** [comment]
Hello @stevensacks , it looks the issue is still there 😢 .
I am using storybook 6.3.13 and `{Story(context)}` doesn’t seem to be a perfect solution.

There will be another issue:  https://github.com/storybookjs/storybook/issues/8426.

I tried to copy `withI18Next.ts` as a file locally and just simply  change `{Story(context)}` to `<Story {...context} />` then the issue has gone.

![image](https://user-images.githubusercontent.com/2525267/149730661-ff20d41b-15bf-43a7-b5eb-cd3b5811faf9.png)

This is pretty hacky I wonder if there is a better way we can do it. Thanks~

**Comment by stevensacks** [comment]
As stated in the [README](https://github.com/stevensacks/storybook-react-i18next#readme), this plugin no longer works with Storybook 6.3. It's now 6.4 up.

**Comment by Cretezy** [comment]
I'm still getting this error with Storybook v6.4.13 and v1.0.16 of this package.

Here's a reproducible example: https://github.com/Cretezy/storybook-react-i18next-issue

**Comment by stevensacks** [comment]
Looks li

**Comment by Cretezy** [comment]
It seems like most addons use `Story()`, and that using `<Story />` is actually the cause of this somewhere in the addon pipeline. IMO, this looks like it's more a bug at the Storybook level, since it _should_ support both (as the docs mention), but something is clearly wrong with the implementation.

**Comment by stevensacks** [comment]
Yes that was my experience, as well.

**Comment by shilman** [comment]
Here's the background for anybody who wants to look into this more deeply:

The `<Story />` call compiles to a `React.createElement` which is sometimes **required** for react hooks to work in stories. 

Storybook preview hooks are a framework-agnostic version of hooks and shouldn't care whether they are rendered inside a React element or not.

This has come up before without a proper solution, and unfortunately I'm not sure what to say this time around either. cc @tmeasday

**Comment by stevensacks** [comment]
@shilman The problem seems to be when you use 3rd-party addons that have a mix of implementations.

I _could_ add a boolean parameter to this addon like `useStoryFn` which would conditionally render `story(context)` vs `<Story {...context}/>` allowing developers to choose which one they want to use.

```jsx
<I18nextProvider i18n={i18n}>
    {useStoryFn ?  {story(context)} : <Story {...context} />}
</I18nextProvider>
```

The issue seems to be more that _other_ addons use one or the other and I can't compensate for that. I can only control what what this addon does.

**Comment by tmeasday** [comment]
I think the issue likely stems from the use of `<Suspense>` in the decorator. Can you explain what's happening there @stevensacks?

**Comment by stevensacks** [comment]
That’s required by react-i18next.

**Comment by michalkleiner** [comment]
Having the same issue. Tried several combinations of everything and couldn't get it working.

**Comment by tmeasday** [comment]
OK, `<Suspense>` was a red herring. The issue was the use of React's `setState` inside a (React) `useEffect` -- the simple fix here is just to use Storybook's versions of these hooks in all cases, and the issue goes away.

In general, there's no reason to use React hooks in a SB decorator.

A more detailed explanation:

The issue comes about when a "hookified" Storybook decorator runs outside of the rendering cycle of a Storybook story. Unsurprisingly, this causes issue with the Storybook hooks, which primarily serve the purpose of giving information about the current SB rendering cycle.

So the problem is, if you have a decorator like: `(Story) => { useGlobals(); return <Story/> }` and it gets **re-run by React, not  Storybook**.

What makes this confusing, is the requirements (to trigger the bug) is that is:
  a) re-run by react
  b) outside of SB's rendering cycle.
  
- To achieve (b), you can use React's `useEffect()` (or even a `setTimeout`).
- To achieve (a), you need two things: (1) to use something like `setState()`, and (2) **the decorator itself must be rendered  as a react element**.

Regarding (a2) this means you won't see the bug if you don't have another decorator that renders as JSX (the criterion that triggered this issue), because otherwise React will end up re-rendering the entire Story in the `setState`, restarting the SB rendering cycle. React re-renders "up to the nearest `<.../>`".

That also gives a hint about how to avoid this problem if you need to use react hooks in a decorator -- use a component to do so:

```js
const myComplexDecorator = (Story) => {
  // you can use SB hooks here.

   return <div>
      <SomeComponentThatUsesReactHooks /> /* <- you can use react hooks
      <Story/>
   </div>
}
```

Because there's JSX "boundary" between `myComplexDecorator` and `SomeComponentThatUsesReactHooks`, those hooks won't trigger problems in `myComplexDecorator`.

**Comment by michalkleiner** [comment]
Thanks for the investigation @tmeasday. In the context of this addon, is it something users should implement within say `preview.js` or this addon needs a change in its https://github.com/stevensacks/storybook-react-i18next/blob/main/src/withI18Next.tsx component?

**Comment by tmeasday** [comment]
The latter @michalkleiner -- just switching that code to use the SB versions of `useEffect`/`useState` and `useRef` should do the trick.

**Comment by stevensacks** [comment]
I've fixed it in the latest release. Also please update Storybook to latest version 6.4.17.

**Comment by michalkleiner** [comment]
Wonderful, thanks @stevensacks, I can confirm this works now. Great work!

**Comment by stevensacks** [comment]
All thanks to @tmeasday!

**Comment by tmeasday** [comment]
Glad to hear it folks! I was glad to have an opportunity for @shilman and I to get our story straight on this :)
